### ISSUE TITLE
Issues communicating with the container

### ISSUE THREAD

**Issue by eugeniominissale** [adilsoncarvalho/gcloud-pubsub-emulator-docker#2]
I'm having issues communicating with the container.
I'm wondering if there is anything else to configure except the `PUBSUB_EMULATOR_HOST` environment variable.
I'm using google-cloud-pubsub to publish in django, in this way:

```
publisher = pubsub.PublisherClient ()
topic_path = publisher.topic_path ('my-project', 'my-new-topic')
topic = publisher.create_topic (topic_path)
topic.publish (topic, request.data ['url']. encode ('utf-8'))
```
but it gives me this exception:

`StatusCode.PERMISSION_DENIED, User not authorized to perform this action.
`
Do I have to set some other environment variable or permissions? The tutorial doesn't explain much more.

Thanks in advance.

**Comment by adilsoncarvalho** [comment]
Hi @eugeniominissale 

Can you post your `docker-compose.yml` file?

**Comment by eugeniominissale** [comment]
Yes. here it is:

```
version: '3'

  hg-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hg-backend
    environment:
      PUBSUB_EMULATOR_HOST: hg-pubsub-emulator:8085
    volumes:
      - ./hg/:/app
    entrypoint: python manage.py runserver 0.0.0.0:8080
    # entrypoint: tail -f /dev/null
    ports:
      - "8080:8080"
    depends_on:
      - hg-db
      - hg-pubsub-emulator

  hg-pubsub-emulator:
    container_name: hg-pubsub-emulator
    image: adilsoncarvalho/gcloud-pubsub-emulator
    ports:
    - "8085:8085"

networks:
  default:
    driver: bridge
```
